CRITICAL - 2021-09-20 10:22:35 --> pg_query(): Query failed: ERROR:  relation &quot;a_menu&quot; does not exist
LINE 2: FROM &quot;a_menu&quot;
             ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\WORKSPACE\\eG...', 170, Array)
#1 C:\WORKSPACE\eGateway_py\gui\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(170): pg_query(Resource id #197, 'SELECT *\nFROM "...')
#2 C:\WORKSPACE\eGateway_py\gui\vendor\codeigniter4\framework\system\Database\BaseConnection.php(715): CodeIgniter\Database\Postgre\Connection->execute('SELECT *\nFROM "...')
#3 C:\WORKSPACE\eGateway_py\gui\vendor\codeigniter4\framework\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM "...')
#4 C:\WORKSPACE\eGateway_py\gui\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 C:\WORKSPACE\eGateway_py\gui\vendor\codeigniter4\framework\system\Model.php(213): CodeIgniter\Database\BaseBuilder->get()
#6 C:\WORKSPACE\eGateway_py\gui\vendor\codeigniter4\framework\system\BaseModel.php(583): CodeIgniter\Model->doFindAll(0, 0)
#7 C:\WORKSPACE\eGateway_py\gui\app\Controllers\BaseController.php(102): CodeIgniter\BaseModel->findAll()
#8 C:\WORKSPACE\eGateway_py\gui\app\Controllers\Home.php(34): App\Controllers\BaseController->common()
#9 C:\WORKSPACE\eGateway_py\gui\vendor\codeigniter4\framework\system\CodeIgniter.php(935): App\Controllers\Home->index()
#10 C:\WORKSPACE\eGateway_py\gui\vendor\codeigniter4\framework\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#11 C:\WORKSPACE\eGateway_py\gui\vendor\codeigniter4\framework\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\WORKSPACE\eGateway_py\gui\public\index.php(45): CodeIgniter\CodeIgniter->run()
#13 C:\WORKSPACE\eGateway_py\gui\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\WORKSPACE\\eG...')
#14 {main}
CRITICAL - 2021-09-20 10:22:37 --> pg_query(): Query failed: ERROR:  relation &quot;a_menu&quot; does not exist
LINE 2: FROM &quot;a_menu&quot;
             ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\WORKSPACE\\eG...', 170, Array)
#1 C:\WORKSPACE\eGateway_py\gui\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(170): pg_query(Resource id #197, 'SELECT *\nFROM "...')
#2 C:\WORKSPACE\eGateway_py\gui\vendor\codeigniter4\framework\system\Database\BaseConnection.php(715): CodeIgniter\Database\Postgre\Connection->execute('SELECT *\nFROM "...')
#3 C:\WORKSPACE\eGateway_py\gui\vendor\codeigniter4\framework\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM "...')
#4 C:\WORKSPACE\eGateway_py\gui\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 C:\WORKSPACE\eGateway_py\gui\vendor\codeigniter4\framework\system\Model.php(213): CodeIgniter\Database\BaseBuilder->get()
#6 C:\WORKSPACE\eGateway_py\gui\vendor\codeigniter4\framework\system\BaseModel.php(583): CodeIgniter\Model->doFindAll(0, 0)
#7 C:\WORKSPACE\eGateway_py\gui\app\Controllers\BaseController.php(102): CodeIgniter\BaseModel->findAll()
#8 C:\WORKSPACE\eGateway_py\gui\app\Controllers\Home.php(34): App\Controllers\BaseController->common()
#9 C:\WORKSPACE\eGateway_py\gui\vendor\codeigniter4\framework\system\CodeIgniter.php(935): App\Controllers\Home->index()
#10 C:\WORKSPACE\eGateway_py\gui\vendor\codeigniter4\framework\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#11 C:\WORKSPACE\eGateway_py\gui\vendor\codeigniter4\framework\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\WORKSPACE\eGateway_py\gui\public\index.php(45): CodeIgniter\CodeIgniter->run()
#13 C:\WORKSPACE\eGateway_py\gui\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\WORKSPACE\\eG...')
#14 {main}
CRITICAL - 2021-09-20 10:53:32 --> Undefined property: App\Controllers\Backup::$load
#0 C:\WORKSPACE\eGateway_py\gui\app\Controllers\Backup.php(11): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'C:\\WORKSPACE\\eG...', 11, Array)
#1 C:\WORKSPACE\eGateway_py\gui\vendor\codeigniter4\framework\system\CodeIgniter.php(935): App\Controllers\Backup->index()
#2 C:\WORKSPACE\eGateway_py\gui\vendor\codeigniter4\framework\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Backup))
#3 C:\WORKSPACE\eGateway_py\gui\vendor\codeigniter4\framework\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\WORKSPACE\eGateway_py\gui\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\WORKSPACE\eGateway_py\gui\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\WORKSPACE\\eG...')
#6 {main}
CRITICAL - 2021-09-20 13:48:03 --> Undefined variable: stacks
#0 C:\WORKSPACE\eGateway_py\gui\app\Views\v_home.php(11): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\WORKSPACE\\eG...', 11, Array)
#1 C:\WORKSPACE\eGateway_py\gui\vendor\codeigniter4\framework\system\View\View.php(220): include('C:\\WORKSPACE\\eG...')
#2 C:\WORKSPACE\eGateway_py\gui\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\WORKSPACE\eGateway_py\gui\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('v_home', Array, true)
#4 C:\WORKSPACE\eGateway_py\gui\app\Controllers\Backup.php(26): view('v_home')
#5 C:\WORKSPACE\eGateway_py\gui\vendor\codeigniter4\framework\system\CodeIgniter.php(935): App\Controllers\Backup->index()
#6 C:\WORKSPACE\eGateway_py\gui\vendor\codeigniter4\framework\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Backup))
#7 C:\WORKSPACE\eGateway_py\gui\vendor\codeigniter4\framework\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\WORKSPACE\eGateway_py\gui\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 C:\WORKSPACE\eGateway_py\gui\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\WORKSPACE\\eG...')
#10 {main}
CRITICAL - 2021-09-20 13:55:04 --> Invalid file: v_list.php
#0 C:\WORKSPACE\eGateway_py\gui\vendor\codeigniter4\framework\system\View\View.php(203): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('v_list.php')
#1 C:\WORKSPACE\eGateway_py\gui\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('v_list', Array, true)
#2 C:\WORKSPACE\eGateway_py\gui\app\Controllers\Backup.php(27): view('v_list')
#3 C:\WORKSPACE\eGateway_py\gui\vendor\codeigniter4\framework\system\CodeIgniter.php(935): App\Controllers\Backup->index()
#4 C:\WORKSPACE\eGateway_py\gui\vendor\codeigniter4\framework\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Backup))
#5 C:\WORKSPACE\eGateway_py\gui\vendor\codeigniter4\framework\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\WORKSPACE\eGateway_py\gui\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 C:\WORKSPACE\eGateway_py\gui\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\WORKSPACE\\eG...')
#8 {main}
CRITICAL - 2021-09-20 14:05:14 --> dir() expects at least 1 parameter, 0 given
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'dir() expects a...', 'C:\\WORKSPACE\\eG...', 28, Array)
#1 C:\WORKSPACE\eGateway_py\gui\app\Controllers\Backup.php(28): dir()
#2 C:\WORKSPACE\eGateway_py\gui\vendor\codeigniter4\framework\system\CodeIgniter.php(935): App\Controllers\Backup->index()
#3 C:\WORKSPACE\eGateway_py\gui\vendor\codeigniter4\framework\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Backup))
#4 C:\WORKSPACE\eGateway_py\gui\vendor\codeigniter4\framework\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\WORKSPACE\eGateway_py\gui\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 C:\WORKSPACE\eGateway_py\gui\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\WORKSPACE\\eG...')
#7 {main}
CRITICAL - 2021-09-20 14:06:12 --> dir(C:\WORKSPACE\eGateway_py\gui\public../writable/uploads/backups,C:\WORKSPACE\eGateway_py\gui\public../writable/uploads/backups): The system cannot find the path specified. (code: 3)
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'dir(C:\\WORKSPAC...', 'C:\\WORKSPACE\\eG...', 28, Array)
#1 C:\WORKSPACE\eGateway_py\gui\app\Controllers\Backup.php(28): dir('C:\\WORKSPACE\\eG...')
#2 C:\WORKSPACE\eGateway_py\gui\vendor\codeigniter4\framework\system\CodeIgniter.php(935): App\Controllers\Backup->index()
#3 C:\WORKSPACE\eGateway_py\gui\vendor\codeigniter4\framework\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Backup))
#4 C:\WORKSPACE\eGateway_py\gui\vendor\codeigniter4\framework\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\WORKSPACE\eGateway_py\gui\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 C:\WORKSPACE\eGateway_py\gui\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\WORKSPACE\\eG...')
#7 {main}
CRITICAL - 2021-09-20 14:06:30 --> dir(C:\WORKSPACE\eGateway_py\gui\public..\writable\uploads\backups,C:\WORKSPACE\eGateway_py\gui\public..\writable\uploads\backups): The system cannot find the path specified. (code: 3)
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'dir(C:\\WORKSPAC...', 'C:\\WORKSPACE\\eG...', 28, Array)
#1 C:\WORKSPACE\eGateway_py\gui\app\Controllers\Backup.php(28): dir('C:\\WORKSPACE\\eG...')
#2 C:\WORKSPACE\eGateway_py\gui\vendor\codeigniter4\framework\system\CodeIgniter.php(935): App\Controllers\Backup->index()
#3 C:\WORKSPACE\eGateway_py\gui\vendor\codeigniter4\framework\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Backup))
#4 C:\WORKSPACE\eGateway_py\gui\vendor\codeigniter4\framework\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\WORKSPACE\eGateway_py\gui\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 C:\WORKSPACE\eGateway_py\gui\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\WORKSPACE\\eG...')
#7 {main}
CRITICAL - 2021-09-20 14:16:49 --> dir(C:\WORKSPACE\eGateway_py\gui\public\..\writable\uploads\backups,C:\WORKSPACE\eGateway_py\gui\public\..\writable\uploads\backups): The system cannot find the file specified. (code: 2)
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'dir(C:\\WORKSPAC...', 'C:\\WORKSPACE\\eG...', 25, Array)
#1 C:\WORKSPACE\eGateway_py\gui\app\Controllers\Backup.php(25): dir('C:\\WORKSPACE\\eG...')
#2 C:\WORKSPACE\eGateway_py\gui\vendor\codeigniter4\framework\system\CodeIgniter.php(935): App\Controllers\Backup->index()
#3 C:\WORKSPACE\eGateway_py\gui\vendor\codeigniter4\framework\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Backup))
#4 C:\WORKSPACE\eGateway_py\gui\vendor\codeigniter4\framework\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\WORKSPACE\eGateway_py\gui\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 C:\WORKSPACE\eGateway_py\gui\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\WORKSPACE\\eG...')
#7 {main}
CRITICAL - 2021-09-20 14:17:03 --> dir(C:\WORKSPACE\eGateway_py\gui\publicdist\upload\backups,C:\WORKSPACE\eGateway_py\gui\publicdist\upload\backups): The system cannot find the path specified. (code: 3)
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'dir(C:\\WORKSPAC...', 'C:\\WORKSPACE\\eG...', 25, Array)
#1 C:\WORKSPACE\eGateway_py\gui\app\Controllers\Backup.php(25): dir('C:\\WORKSPACE\\eG...')
#2 C:\WORKSPACE\eGateway_py\gui\vendor\codeigniter4\framework\system\CodeIgniter.php(935): App\Controllers\Backup->index()
#3 C:\WORKSPACE\eGateway_py\gui\vendor\codeigniter4\framework\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Backup))
#4 C:\WORKSPACE\eGateway_py\gui\vendor\codeigniter4\framework\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\WORKSPACE\eGateway_py\gui\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 C:\WORKSPACE\eGateway_py\gui\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\WORKSPACE\\eG...')
#7 {main}
